namespace Poker.Common;

public static class CardList
{
    public static readonly (Rank Rank, Suit Suit)[] Cards =
    [
        (Rank.Ace, Suit.Spade),
        (Rank.King, Suit.Spade),
        (Rank.Queen, Suit.Spade),
        (Rank.Jack, Suit.Spade),
        (Rank.Ten, Suit.Spade),
        (Rank.Nine, Suit.Spade),
        (Rank.Eight, Suit.Spade),
        (Rank.Seven, Suit.Spade),
        (Rank.Six, Suit.Spade),
        (Rank.Five, Suit.Spade),
        (Rank.Four, Suit.Spade),
        (Rank.Three, Suit.Spade),
        (Rank.Two, Suit.Spade),
        (Rank.Ace, Suit.Hart),
        (Rank.King, Suit.Hart),
        (Rank.Queen, Suit.Hart),
        (Rank.Jack, Suit.Hart),
        (Rank.Ten, Suit.Hart),
        (Rank.Nine, Suit.Hart),
        (Rank.Eight, Suit.Hart),
        (Rank.Seven, Suit.Hart),
        (Rank.Six, Suit.Hart),
        (Rank.Five, Suit.Hart),
        (Rank.Four, Suit.Hart),
        (Rank.Three, Suit.Hart),
        (Rank.Two, Suit.Hart),
        (Rank.Ace, Suit.Club),
        (Rank.King, Suit.Club),
        (Rank.Queen, Suit.Club),
        (Rank.Jack, Suit.Club),
        (Rank.Ten, Suit.Club),
        (Rank.Nine, Suit.Club),
        (Rank.Eight, Suit.Club),
        (Rank.Seven, Suit.Club),
        (Rank.Six, Suit.Club),
        (Rank.Five, Suit.Club),
        (Rank.Four, Suit.Club),
        (Rank.Three, Suit.Club),
        (Rank.Two, Suit.Club),
        (Rank.Ace, Suit.Diamond),
        (Rank.King, Suit.Diamond),
        (Rank.Queen, Suit.Diamond),
        (Rank.Jack, Suit.Diamond),
        (Rank.Ten, Suit.Diamond),
        (Rank.Nine, Suit.Diamond),
        (Rank.Eight, Suit.Diamond),
        (Rank.Seven, Suit.Diamond),
        (Rank.Six, Suit.Diamond),
        (Rank.Five, Suit.Diamond),
        (Rank.Four, Suit.Diamond),
        (Rank.Three, Suit.Diamond),
        (Rank.Two, Suit.Diamond),
    ];
}
